version: '3'
services: 
  mongo:
    image: 'mongo'
    ports:
    - "27017:27017"
    volumes:
      - /data/db
  web:
    image: 'astencavage/storelocator_web:1.0'
    ports: 
    - "3000:3000"
    depends_on: 
    - mongo
    links:
      - mongo
